name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  devopstest:
    runs-on: ubuntu-latest
    container: golang:1.19

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.2
        with:
          repository: ncyellow/GophKeeper-autotest-bin
          latest: true
          fileName: "*"
          out-file-path: .tools

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophkeepertest /usr/local/bin/gophkeepertest
      - name: Build server binary
        run: |
          cd cmd/server
          go build -o server

      - name: "Code increment #1"
        if: always()
        run: |
          gophkeepertest -test.v -test.run=^TestIteration1$ \
            -agent-binary-path=cmd/agent/agent
      - name: Build server binary
        run: |
          cd cmd/server
          go build -o server          